CREATE TABLE accounts
(
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  balance INT DEFAULT 0 NOT NULL
);

CREATE TABLE transactions
(
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	amount INTEGER NOT NULL,
	status VARCHAR(20) NOT NULL,
	source VARCHAR(36) NOT NULL,
  target VARCHAR(36) NOT NULL
);
